### ISSUE TITLE
Issue regarding the use of signed integers as parameters

### ISSUE THREAD

**Issue by ezquire** [ryan-shaw/Garlicoin#3]
![image](https://user-images.githubusercontent.com/20214762/36122023-cffe7c8c-0ffc-11e8-9019-b7323285e782.png)

Your code is on the right, the Lyra2.c original code is on the left, they use a uint64_t, you use an int64_t (which as far as I know is a signed integer and can lead to overflow errors) 

Not a terribly difficult fix, but it is a concern. 

Cheers! Thanks for all your work, I am but a lowly Garlic miner, willing to help where I can

**Comment by ryan-shaw** [comment]
Can you move to GarlicoinOrg/Garlicoin please
